KSP-RO/RealFuels

RealFuels/TantaresLV.cfg

Simple setup based on the standard x5 multiplier.

Add tanks for TantaresLV

---

RealFuels/FuelTanksPlus_modularFuelTanks.cfg
RealFuels/MunarIndustries_modularFuelTanks.cfg
RealFuels/NP2_modularFuelTanks.cfg

Hello.
Adding support for Fuel Tanks Plus by NecroBones and Munar Industries' MFT Expansion.
Also, changed Novapunch's tanks to Cryogenic so that they match their part names/descriptions .
For your consideration.

Novapunch cryo, more tanks

---

RealFuels/Parts/zzz_radiator/part.cfg

Not the best way to do it, but deleting the key/value pair didn't seem to work.
Also removed extra tab at end of (preceding) line.

Removed the radiator's ability to work as a solar panel

---

RealFuels/Resources/ResourceHsps.cfg

Starting a list of specific heats of fuels, as well as vapourization energies where appropriate (cryogenic fuels)
Estimations will be listed as such
Choose your poison NathanKell, how do you want large numbers listed?

Add specific heats for some fuels

---

Source/RealFuels.csproj
Source/RealFuels.userprefs
Source/Tanks/ModuleFuelTanks.cs

Fixed debugging fields (throwing errors when compiling in debug mode)

Fixed debugging fields

---

RealFuels/Resources/RealTankTypes.cfg
Source/Tanks/FuelTank.cs
Source/Tanks/ModuleFuelTanks.cs

* Fixed bug where individual tank insulation/tank values weren't loading
in.
* Increased heat leak flux based on  part thermal mass (total) / part
thermal mass - resource mass.
* Tweaked ServiceModule and Default tank insulation values.

10.7.1 bug fixes

---

Source/Tanks/ModuleFuelTanks.cs

boil-off adjustments

---

Source/Engines/ModuleEnginesRF.cs

* Use FlightLogger LogEvent(string) instead of FlightLogger eventLog
hack

Use FlightLogger LogEvent(string)

---

RealFuels/Resources/RealTankTypes.cfg

* Added boiloff product to service modules.

Added boiloff product to service modules

---

Source/Engines/ModuleEngineConfigs.cs
Source/Engines/ModuleEnginesRF.cs
Source/RealFuels.csproj
Source/Tanks/TankWindow.cs
Source/Ullage/UllageModule.cs
Source/Utilities/Utilities.cs

I don't claim this is all the changes necessary for 1.2, but it gets a lot of the basics out of the way

Additional 1.2 changes

---

Source/Utilities/TestFlightWrapper.cs

It has multiple AddInteropValue methods, so have to bind with specific
args.  Should fix #169

Fix TestFlightWrapper

---

Source/Engines/ModuleEngineConfigs.cs

Fixes issues with SSTUModularEngineCluster pricing.

Make sure cost only gets multiplied by scale once

---

Source/Tanks/ModuleFuelTanksRF.cs

* Improved Analytic Support
* Cached FlightIntegrator
* Reworked ferocial boil off mode (instead of adjusting Q based on
calculated tank thermalMass / resourceThermalMass ratio, we properly
calculate tank wall temperature by redistributing thermal energy from
resource to part.  (KSP assumes part+resource thermal energy is just one
homogenous temperature)

Improved Analytic Support

---

Source/TestFlightRF/TestFlightRealFuels.cs

Should really be refactored to grab the final string from a method but whatever.

Make burn time formatting consistent between create and append.

---

Source/Engines/ModuleEnginesRF.cs

Dependent on changes in SolverEngines

Fix vacuum thrust info

---

Source/Engines/RFSettings.cs
Source/Tanks/ModuleFuelTanksRF.cs

* Disabled ferociousBoilOff (changed default setting in RFSETTINGS)
* Added missing cooling variable declaration

Disabled ferociousBoilOff

---

Source/Engines/ModuleEnginesRF.cs
Source/Tanks/ModuleFuelTanksRF.cs
Source/Ullage/UllageSet.cs

* Fix for engines not properly loading pressure fed setting from ModuleEngineConfig
* Fix for cryogenic tanks exploding during analytic mode after long periods unloaded.

Pressure Fed engine fix + Analytic boiloff fix

---

Source/Engines/ModuleEngineConfigs.cs
Source/Engines/ModuleEnginesRF.cs
Source/TestFlightRF/TestFlightRealFuels.cs
Source/Ullage/UllageSimulator.cs

These are a bunch of changes I made a while ago that improved quality of life for me. I haven't done anything with these for a while, so I figured I might as well get around to submitting a PR to see whether the changes are useful for anyone else.

Opinionated tweaks

---

Source/Tanks/ModuleFuelTanks.cs

It can get (and has been) confusing at times with so many mods adding to the PAW.

Changed Show UI and Hide UI to Show Tank UI and Hide Tank UI

---

Source/Engines/ModuleEngineConfigs.cs

This should fix the issues with symmetric parts mentioned in #219 and the unreliable click-through blocking with more than one engine.

Engine GUI fixes

---

Source/Tanks/ModuleFuelTanks.cs

This partially reverts commit 97519a262777149b97973381f4a3f13bc160b7cb.
This should fix #232

Partially revert "further changes to how upgrade nodes are (not) treated"

---

Source/EntryCosts/UpgradeManager.cs

Required for getting accurate entry cost over multiple parts with shared ECMs.

Add method for getting entry cost over multiple parts/ECMs

---

Source/EntryCosts/Initializer.cs
Source/EntryCosts/UpgradeManager.cs

Fixes https://github.com/KSP-RO/RP-0/issues/1460

Fix bulk part purchases not deducting funds correctly

---

Source/Engines/SolverRF.cs

Its really only this one string MechJeb cares about in this API and drop
a better clue as to why.

Slightly more descriptive comment

---

Source/Tanks/ModuleFuelTanksRF.cs

Only update boiloff stats for parts that have the PAW open

---

Source/EntryCosts/EntryCostDatabase.cs
Source/EntryCosts/UpgradeManager.cs

Will be used by RP0KCT to find the correct entry cost total over multiple parts.

Add EntryCostManager.EntryCostForParts()

---

RealFuels/Resources/ResourceHsps.cfg

Move resource thermal data to RF from RO, and add data for resources which lacked it.
RO PR: https://github.com/KSP-RO/RealismOverhaul/pull/2614

Improve resource thermal data

---

Source/Tanks/ModuleFuelTanks.cs
Source/Tanks/TankDefinition.cs
Source/Tanks/TankDefinitionSelectionGUI.cs
Source/Utilities/Utilities.cs

* Add title support for tank defs
* Color tank def names based on whether they are unlockable (i.e the prerequisite tech has been researched)
Needs to be released together with https://github.com/KSP-RO/RP-0/pull/1828.

Tank definition picker improvements

---

Source/Tanks/FuelTank.cs
Source/Tanks/TankWindow.cs

Was removed by accident in 2692a852e3c935078b8f5cdde633559da0305249

Clamp fuel amount to stay within the max volume

---

Source/Engines/ModuleEngineConfigs.cs
Source/Tanks/ModuleFuelTanks.cs

This is actually pretty expensive on high part count vessels.

Do not run UpdateUsedBy logic outside Editor

---

Source/Tanks/ModuleFuelTanks.cs

Need this to detect tank definition changes in Procedural Avionics.

Add OnTankDefinitionChanged event

---

RealFuels/Localization/en-us.cfg

when used as a verb, "to ullage" actually means to create more ullage, aka create more space in the tank (and there are some other vague definitions of it, but none that pertain to this)
https://www.merriam-webster.com/dictionary/ullage (noun only)
https://www.dictionary.com/browse/ullage (noun and verb)
https://www.collinsdictionary.com/us/dictionary/english/ullage (noun and verb)
https://en.wiktionary.org/wiki/ullage (noun and verb)
will test this out in game in a bit to make sure it works

fixing ullage grammar issues

---

Source/Tanks/ModuleFuelTanks.cs

Fixes https://github.com/KSP-RO/RP-1/issues/2313

Support 0 volume tanks without bad things happening
