- RealFuels/TantaresLV.cfg
I should've done this in the first place, to prevent accidental conflicts.
> Add NEEDS[!RealismOverhaul] to TantaresLV tanks

- RealFuels/KSPI_RF.cfg
The KSPI file seems to be the only one that used the "&" operator. Simple find-and-replace.
> Replacing "&" with "," for the newest ModuleManager

- ModularFuelTanks/KW_modularFuelTanks.cfg
Updated MM config for KW Rocketry v2.6d2:
* added missing tanks (5m, unpainted and L0.5 tanks)
* changed volumes to match KW rebalancing
also
* changed "Cryogenic" tanks to "Default"
Note: Some volumes now have decimal fractions in volume, which may not be desirable.
> Updated MM config for KW Rocketry v2.6d2.

- RealFuels/RSCapsuledyne.cfg
- RealFuels/RealFuels_MkIVSystem.cfg
- RealFuels/RetroFuture_modularFuelTanks.cfg
- RealFuels/SXT.cfg
- RealFuels/SpaceplanesPlus.cfg
- RealFuels/Squad_modularFuelTanks.cfg
Hello,
Please let me know if I messed up. Here's a list of things I did:
-Multiplied the RSCapsuledyne's tank by 5 to be more in line with other RF tanks
-Added a bunch of missing Squad Mk3 parts/adapters as Fuselages
-Added a missing Mk IV tank as Fuselage
-Added a couple SXT parts as Fuselages
Question:  How does one go about determining which tanks should be Default/Cryogenic/BalloonCryo/etc.? I know Fuselage/Xenon/ServiceModule is pretty self-explanatory but what about the rest?
For your consideration.
> Missing tanks for stock, RetroFuture, and SXT

- RealFuels/Sea_Dragon2_tanks.cfg
Made volume match size when compared to a stretchy tank. Modified Stage 1 tank basemass to give Stage 1 mass fraction similar to "real" Sea Dragon.
> Sea Dragon 2 tanks

- RealFuels/RealFuels_MkIVSystem.cfg
Multiplies tank contents by 5 and changes them into a RF tank with the appropriate type, nukes fuel switch but not mesh switch modules.
> Update configs for Nertea's MKIV system

- RealFuels/Readme_RF.txt
- Source/Tanks/ModuleFuelTanks.cs
* Fixed error in heat leakage equation. (misplaced parentheses)
* Removed conduction factor compensations. (maybe temporarily maybe not)
* Added compensation for resource thermal mass to boiloff heat flux
* Disabled context menu debugging messages relating to new boiloff code. (debug1Display / debug2Display - configurable debuggers). Moved it behind #if DEBUG
> Fixed error in heat leakage equation

- Source/Tanks/ModuleFuelTanks.cs
* Compensated for PhysicsGlobals.ConductionFactor (stock value of 20x is way too much boiloff for the default tank which is supposed to approximate Saturn V rates)
> Compensated for PhysicsGlobals.ConductionFactor

- RealFuels/Resources/RealTankTypes.cfg
- Source/RealFuels.csproj
- Source/RealFuels.sln
- Source/RealFuels.userprefs
- Source/Tanks/MFSSettings.cs
- Source/Tanks/ModuleFuelTanks.cs
- Source/TechLevels/TechLevel.cs
- Source/TweakScale_RealFuels.csproj
* Increased boiloff rate can be switched off by adding ferociousBoilOff
= False to MFSSETTINGS (best use MM patch for that)
* PhysicsGlobal.conductionFactor can be compensated for by adding 
globalConductionCompensation  = true to MFSSETTINGS (not recommended but 
made available)
* cryogenic outerInsulation improved to 0.0005 (previous value 0.01)
* All LOX tanks now assume stainless steel tanks, except the ServiceModule.
> Last 1.0.4 update

- Source/Engines/ModuleEngineConfigs.cs
- Source/Engines/ModuleEnginesRF.cs
- Source/Engines/RFSettings.cs
- Source/Engines/UpgradeManager.cs
- Source/Tanks/TankWindow.cs
**This is for KSP 1.1**
Fixed issues in the GUI that were causing crashes.  RF and MFT appear to be working fine for me in 1. now, though I have not done any **extensive** testing.  What I did do was verify proper operation on the VAB, then launch a rocket.  I launched a rocket both with and without tanks filled to ensure that worked as expected.
Note that due to IDE differences, and managed path differences, this PR is a code change only.  References will need to be updated by the project maintainers.  Looks like the only change I made to references was to remove KSPAPIExtensions
> KSP 1.1 Fixes - Mostly GUI

- Source/Tanks/ModuleFuelTanks.cs
Change boiloff to use wetted tank area instead of total tank area for wall-propellant conduction purposes.
> Change boiloff to use wetted tank area

- Source/Engines/ModuleEngineConfigs.cs
- Source/RealFuels.csproj
- Source/Tanks/TankWindow.cs
- Source/Utilities/Styles.cs
Added a couple GUI styles based on TestFlight's style.  Setup the Tank and Engine GUIs to use these for panels and tooltips.
This makes the windows and more importantly the Tooltips about a billion times easier to actually read.
> Added GUI Styles and updated Engine and Tank editor GUIs

- Source/Engines/RFSettings.cs
- Source/Tanks/FuelTank.cs
- Source/Tanks/MFSSettings.cs
- Source/Tanks/ModuleFuelTanks.cs
* Moved some settings from MFSSETTINGS. (were meant to be in RFSETTINGS
and weren't being set)
* Added tank area cache fields to FuelTank so we're not recalculating
these every frame when they never change.
* Changed debug fields to use RFSETTINGS.debugBoiloff so I don't have to
compile a debug plugin just to watch boiloff. (and so players can use
this too)
* Changes to individual tank surface area calculation: Assume a sphere
if tankRatio <= 0.125 (maybe increase this to 0.25 - 0.5) (this can
still be improved further, previous method was overly simplistic and 
fails for very small tanks)
> Surface Area changes

- RealFuels/Resources/ResourceHsps.cfg
- Source/Tanks/FuelTank.cs
- Source/Tanks/MFSSettings.cs
- Source/Tanks/ModuleFuelTanks.cs
* Added support for boiloff product:  Tanks can be now be configured to produce a resource as their contents boiloff. (i.e. gaseous hydrogen from liquid hydrogen). Requires a tank capable of receiving the resource.
* Factored in resource conductivity to heat leakage calculation. (impact on boiloff rates is marginal at best)
* Changed new surface area code to just use the greater of two calculations: The older simplified code and spherical tank code. By volume, nothing should have lower surface area than a sphere so if it's lower then go with sphere.
* Added conductivity values to several cryo resources.
* Added :FOR[RealFuels] to several of them in keeping with other RF resource config patches.
> Added boiloff product and resource conductivity

- Source/Engines/ModuleEnginesRF.cs
Curve was being set to null then an error message was saying that it was
null and recreating it.  It is being initialized in field initializer so
there is no need to initialize it again, just make sure it isn't set to
null.
Fixes #171
> Fix noisy but harmless error message

- Source/Engines/UpgradeManager.cs
Current code makes it so that if an upgrade containing a config isn't
found, when the engine GUI is open, it spams debug messages trying to
find the upgrade.  This makes it so that it just assumes that the
upgrade is unlocked.  Not every config is going to have an upgrade node.
> Fix upgrade manager unnecessary errors

- Source/Engines/ModuleEngineConfigs.cs
- Source/Engines/ModuleEnginesRF.cs
This allows you to retry if ignition failed, as long as you're still on
the pad (and thus motivates stage-and-a-half designs like Atlas Classic,
or parallel-staged designs like the R-7).
However, ignitions (and ignitionResources) will still be consumed, so if
you have a multi-ignition first stage engine, this won't be what you
want.  I decided not to bother adding extra complications to deal with
this, as it seems a fairly uncommon case (by the time restartable first
stage engines like the Merlin are developed, ignition reliability is
basically 1).
Because one use case for this is making some engines only ignitable on
the pad (ignitions=0), have a special case for this in GetInfo output.
Also, add a flag field to ModuleEngineConfigs which, if set, specifies
that ignitions=0 actually means …
> Always allow ignition while attached to launch clamps

- Source/Engines/SolverRF.cs
Fixes issue #180  by removing term t0 from chamberTemp non-combusting calculation. As far as I can tell, t0 is the ambient stagnation temperature? But I'm seeing it spike over 1000000K even sitting on the pad if an engine is decoupled. I usually see this on SRBs but have seen reports of it happening on liquid engines as well.
> Fix for issue #180

- Source/Tanks/ModuleFuelTanksRF.cs
* Reinstating analytic handling of boiloff. part.temperature no longer
frozen during analytic mode. part.analyticInternalInsulationFactor set
based on tank.outerInsulationFactor (may need adjusting)
* Boiloff calculation uses InternalFluxAdjust during analytical mode
instead of adjusting internal flux directly.
> Reinstating analytic handling of boiloff

- Source/Engines/RFSettings.cs
- Source/RealFuels.csproj
- Source/RealFuels.userprefs
- Source/Tanks/ModuleFuelTanksRF.cs
* Reinstating analytic handling of boiloff. part.temperature no longer 
frozen during analytic mode. part.analyticInternalInsulationFactor set 
based on tank.outerInsulationFactor (may need adjusting)
* Boiloff calculation uses InternalFluxAdjust during analytical mode 
instead of adjusting internal flux directly.
* Cached FlightIntegrator
* Reworked ferocial boil off mode (instead of adjusting Q based on 
calculated tank thermalMass / resourceThermalMass ratio, we properly  
calculate tank wall temperature by redistributing thermal energy from 
resource to part.  (KSP assumes part+resource thermal energy is just one 
homogenous temperature)
> Analytic boiloff changes

- Source/Pumps/RefuelingPump.cs
- Source/Tanks/ModuleFuelTanksRF.cs
* Fuel pumps must now be present and active in order to avoid boiloff during prelaunch (previously being on the launch pad was enough)
* Fuel pumps are now enabled by default and enabled setting respects symmetry in the editor
* Streamline fuel pump enable/disable UI - now a simple button rather than display + button
> Pump changes

- Source/Pumps/RefuelingPump.cs
- Source/Tanks/ModuleFuelTanksRF.cs
My recent changes to launch clamp behavior caused tanks to start near 300K rather than fuel temperature.  This causes higher boiloff (initially) than you should have.
> Boiloff fix

- RealFuels/Squad_modularFuelTanks.cfg
**Change Log:**
* Add the new Rockomax and toroidal tank patches as subsets of the old ones (identical parts).
* Add patches for the new spherical and capsule tanks.
* Add patch for the missed NCS Adapter tank.
**Notes:**
* Volumes were calculated based upon the model mesh dimensions and adjusted to be 86% of the overall tank volume. This may be a completely wrong assumption though so some feedback is required.
> [Mod Support] Update for the KSP 1.4 tanks

- Source/Tanks/ModuleFuelTanks.cs
- Source/Tanks/TankWindow.cs
Primarily, this PR stops the frequent FAR re-voxelizations reported in #221.  That issue also seemed to be associated with garbage collection stalls on my machine, but I don't know why. Heap fragmentation from FAR maybe?
After that was dealt with, the GUI was noticiably laggier with **un**configured tanks than with configured ones.  Some part of formatting the potential tank volume and resource mass for display is apparently expensive, so I hoisted it out of OnGUI.
Finally, the formula for calculating masses of additional tank options was not right.  It's still off by a tiny bit, I think because adding resources changes dry mass, but it's a lot better.
> Gui perf fixes

- Source/Tanks/ModuleFuelTanks.cs
This wasn't checking whether the found definition is even available on the current tank.
> Fix tank definition fallback mechanic.

- Source/Makefile
- Source/assembly/Checkers.cs
This PR makes the minimal required changes to make this mod work on KSP 1.8. I am a Linux user and have no access to a Windows machine to test or build there. I was also unable to get the IDE solution to work at all on MonoDevelop. I suspect this last issue is just my own lack of knowledge of how MonoDevelop works.
Here is my testing plan (checked items are already done):
Tell me if there is anything I could to do help with this.
PS: I'm mostly just scratching my own itch, as with many open-source contributions, so I will happily just use my local build, so no need to rush this.
> Update for KSP 1.8

- RealFuels/RealFuels.version
The version file currently has a syntax error, a comma is missing.
Now it's fixed.
In case you're interested, @DasSkelett has developed a version file validator plugin for GitHub that can catch things like this before release, might be worth trying out:
- https://github.com/DasSkelett/AVC-VersionFileValidator
> Fix missing comma in version file

- Source/Engines/ModuleEngineConfigs.cs
- Source/Engines/ModuleEnginesRF.cs
- Source/Utilities/Utilities.cs
This makes the module info and engine config info in the editor show more useful units and numbers rather than the default kN, which made comparing ion engines thrust almost impossible. It now shows varying units from kN to μN. Examples:
> Show more appropriate units for thrust in module display info

- Source/Tanks/ModuleFuelTanksRF.cs
- Source/Utilities/Utilities.cs
Uses kerbalism's API to produce boiloff product (when present) to avoid the "incoherent behaviour" message.
Needs more testing. I've found it to work fine, but no one outside of me has (to my knowledge tested it).
> Use kerbalism's resource system when installed

- Source/Tanks/FuelTankList.cs
- Source/Tanks/ModuleFuelTanks.cs
- Source/Tanks/TankDefinition.cs
- Source/Tanks/TankWindow.cs
Move all editor PAW fields into a group.
Change tank UI logic to be more robust.
Additional updates to connected parts to address #242.
> Improve GUI window handling

- Source/Tanks/FuelTankList.cs
- Source/Tanks/ModuleFuelTanks.cs
- Source/Tanks/TankDefinition.cs
This removes empty tank nodes from craft and save files to reduce file sizes and load times.
Functionality is unaffected; any missing nodes are populated with defaults when the tank list is loaded.
> Remove empty tank nodes from save file

- Source/Engines/ModuleEnginesRF.cs
Pressure-fed engines were only displaying the pressurization state, even if they required ullage.  Fix prioritization to show error case (insufficient pressure), then ullage state if applicable, then non-error cases.
Please squash+merge and fix the typo in the commit.
> Display Ullage Status When Pressure-Fed

- Source/Tanks/ModuleFuelTanks.cs
Fixes #255
KSP after 1.8 is cacheing more PAW fields.  In 1.10, the created event buttons hang around and don't get cleared by PAW creation, only by refresh.  Catch the PAW show event and request a refresh if one is requested.
Refactor UpdateUsedBy a little.  Every tank PartModule iterating over every vessel PartModule to build the UsedBy mapping may need analysis
> Handle PAW Field Caching

- Source/Tanks/TankDefinition.cs
It would be used in RP-1 for requiring the player to pay an entry cost before a tank definition becomes selectable.
> Added option that allows unlocking TankDefinition with a PartUpgrade

- Source/Engines/ModuleEngineConfigs.cs
- Source/Utilities/Utilities.cs
This patch adds optional B9PartSwitch integration for RealFuels, in the form of automatic variant switching based on engine config. It is entirely optional and does not have any effect if B9PartSwitch is not installed.
Parts can opt-in to B9PS integration by adding the `b9psModuleID` key to its `ModuleEngineConfigs`. If so, each `CONFIG` must have a `b9psSubtypeName` key, indicating the B9PS subtype that should be used for that particular variant. RealFuels will then access the specified B9PS module via reflection and set the subtype accordingly, if B9PS is installed. The selector UI for that particular B9PS module will be disabled, as it is managed by RealFuels.
The primary use-case for this integration is to enable switching of Waterfall plumes based on engine configuration. In "stock" …
> Add optional B9PartSwitch integration

- Source/Engines/ModuleEngineConfigs.cs
This way, ex. plume and model switching could be implemented separately.
The modules and subtypes are now defined in `CONFIG`s, using `LinkB9PSModule` _nodes_. The node contains 2 keys, `name` and `subtype`. The presence of a single `Link` node with a given `name` signifies that RF should be managing the corresponding module, so _all_ configs must specify a subtype for that module.
This is not backwards-compatible with the original PR, but I doubt anyone will be broken by it.
Example:
```text
@MODULE[ModuleEngineConfigs]
{
@CONFIG[blah]
{
%LinkB9PSModule[SwitcherA] { subtype = foo }
%LinkB9PSModule[SwitcherB] { subtype = bar }
}
// Etc. for other configs.
}
```
cc @DRVeyl -- thanks for the help!
> Extend B9PS integration to support switching of multiple modules

- Source/Engines/ModuleEnginesRF.cs
It is common for players to see the "Ground lit only" string but not realize this means it requires clamps, and be confused.  This change clarifies things a bit by changing the string to be "Ground Support Clamps" for the Ignition text.
> Updated ground lit info string

- Source/Engines/ModuleAnimatedBimodalEngine.cs
- Source/Engines/ModuleEngineConfigs.cs
- Source/Engines/ModulePairedConfigEngine.cs
- Source/RealFuels.csproj
This module is a hybrid of `ModuleHybridEngine` and `ROLDeployableEngine`. It ties configs into pairs of (primary, secondary)
and allows toggling only within a pair during flight. The transition can optionally be animated.
A "primary" config can declare a linked "secondary" config using the `secondaryConfig` key. All configs must be linked into such pairs, without any unlinked configs leftover and without any config linked to more than one other config.
The UI is modified so that only the primary configurations are selectable. To access the secondaries, a toggle button is added at the top. It also overrides the unlock logic: When unlocking or using a new primary config, the secondary will be auto-unlocked for free (since it doesn't make logical sense for the two modes to have different …
> Introduce `ModuleAnimatedBimodalEngine`

- Source/Engines/ModuleEngineConfigs.cs
- Allow management of multiple gimbal transforms
- Store the default gimbal values for all modules, so that they can be restored when a config without gimbal overrides is selected
This introduces a new notation for specifying overrides for multiple gimbal transforms, which takes precedence over the old `gimbalRange`, `gimbalRangeXP`, &c. in `CONFIG` notation. The new form is a `GIMBAL` node, containing the `gimbalTransform` key and the normal gimbal range keys. There can be arbitrarily many `GIMBAL` keys in a single `CONFIG`.
If a `CONFIG` does not specify a `GIMBAL` (or a plain `gimbalRange`) for a certain transform, then the default value (as specified in the original `ModuleGimbal`) will be applied. This lifts the requirement (bug, really) that if one config specifies a gimbal …
> Gimbal management overhaul

- Source/Engines/SolverRF.cs
Changed normal distribution to reroll if it falls outside the desired range, instead of clamping it. This avoids a problem where the edge value of the interval was more likely to occur than some values closer to the mean.
Changed the weights in `varianceIsp` to have the correct variance of `1`.
> Corrections to probabilities found when looking for variance bug

- Source/Engines/ModuleEnginesRF.cs
Display the 'effective spool-up time' in the PAW, when the engine is not an SRB. That is, the total spool-up time from 0% to 100%, minus the total amount of fractional thrust produced during spool-up converted to the equivalent amount of time firing at full thrust.
Graphically, the actual spool-up curve:
```
|          .-----
|        /
|      /
|.---'
+----------------> time
|~~~~~~~~~~|       total spool-up time
```
is treated as:
```
|       ---------
|       |
|       |
|_______|
+----------------> time
|~~~~~~~~~~|       total spool-up time with original curve
|~~~~~~~|          effective spool-up time  <--
|~~|       equivalent amount of thrust as produced by the original curve, but at 100%
```
> Display 'effective spool up time' in the PAW

- Source/Engines/ConfigFilters.cs
- Source/Engines/ModuleBimodalEngineConfigs.cs
- Source/Engines/ModuleEngineConfigs.cs
- Source/Engines/ModuleEnginesRF.cs
- Source/Engines/ModulePatchableEngineConfigs.cs
- Source/RealFuels.csproj
Adds a system to allow filters to be added to change what configs are displayed. All configs continue to exist even if they are not shown.
Hides configs in the selector GUI, but also in the part info box
Filters are attached as `Func<ConfigNode, bool>` added to `ConfigFilters.Instance.configDisplayFilters`.
> Add config display filters support

- Source/Engines/ModuleEnginesRF.cs
- Source/Ullage/UllageModule.cs
- Source/assembly/AssemblyInfoRF.in
Feature was moved into guiUnits of another KSPField.  Don't reference it anymore.
> Bugfix: SolverEngines removed engineTempString

- Source/Engines/ModuleEngineConfigs.cs
- Source/Utilities/Utilities.cs
This also means that we now allow selecting configs despite tech status or whether the entry cost has been paid.
> Integrate with the config validation feature from RP0KCT

- RealFuels/RealFuels.version
Hi @siimav,
We just got this notification in the CKAN Discord:
That means there's a syntax error in the version file of the latest release (note that this will prevent that release from being added to CKAN). This pull request fixes it.
To catch problems like this before release next time, consider using @DasSkelett's version file validator action:
- https://github.com/DasSkelett/AVC-VersionFileValidator
> Fix version file syntax error

- RealFuels/NearFuture_Propulsion_modularFuelTanks.cfg
- RealFuels/Resources/ResourceHsps.cfg
Hi @NathanKell,
This is like KSP-RO/RealismOverhaul#2612 but for RealFuels.
Referencing KSP-CKAN/CKAN/pull/3525 so I can find this again later easily.
Just two fixes: a deletion with a missing `{}`, and an extra `|`.
> Fix cfg syntax errors

- RealFuels/Resources/ResourceHsps.cfg
Remove MM patches that incorrectly used `:FOR[RealismOverhaul]`
Resolves https://github.com/NathanKell/ModularFuelSystem/pull/290
> Remove references to RO

- RealFuels/MFSSettings.cfg
Exclude Ablator, Enriched Uranium and Uranium Nitride from RF auto-fill so it works correctly with the RS-68 and NTRs.
> Exclude Ablator, Uranium

- RealFuels/Resources/ResourceHsps.cfg
Improve fluid property definitions based on various sources, and also label correct densities for fluids which have wrong densities defined in CRP (for future correction, hopefully).
Accompanies https://github.com/KSP-RO/RealismOverhaul/pull/2830
> Improve fluid properties

- Source/Tanks/ModuleFuelTanks.cs
Takes a ConfigNode and parses that to modify an exisiting MFT.
Can e.g. be used to set different volumes for different lengths, or hooked up to an engine config to enable different props/volumes etc
> Add support for loading config nodes from B9PS

- RealFuels/Localization/en-us.cfg
The original message was difficult to understand by new players because it didn't mention ullage, fuel stability and didn't teach that the fuel actually floats in the tank.
> Added more informative explanation for vapor in feedlines

- RealFuels/SquadExpansion_modularFuelTanks.cfg
Added config that makes Making History Fuel Tanks usable in RO , the volumes were missing they have been calculated .
> Adds support for Making History fuel tanks

- Source/Engines/ModuleEnginesRF.cs
- Source/Ullage/UllageSet.cs
- Source/Ullage/UllageSimulator.cs
Introduces GetPropellantProbability/GetUllageProbability to get the rounded version that forces veryStable to 100% (couldn't think of a better name, even though this isn't really the proper probability since the exponent isn't applied).
This lets MJ 'see' values between 0.996 and 1.0
Didn't get this compiling yet because of all the RF deps and ROUtils in particular so be a little careful before merging.
> Expose propellantStability directly without rounding

- Source/Engines/ModuleEngineConfigs.cs
- Source/Engines/ModuleEnginesRF.cs
- Source/Tanks/ModuleFuelTanks.cs
- Source/Utilities/Utilities.cs
> Add ResetIgnitions() method to MERF

- Source/Engines/ModuleEnginesRF.cs
Problem is that Revert To Launch will use a state that is captured after the random got seeded. This means that all reverts get the exact same engine performance. This in turn means that people may get overly confident in their design being able to cope with thrust offsets and having the performance needed.
> Always recalculate seed in prelaunch

- Source/Tanks/ModuleFuelTanks.cs
This makes it so resources on a tank are scaled according to the new volume set in a B9PS patch.
Currently the volume is simply set without doing anything to the resources present.
This can lead to negative available volume, and is not how other mods that scale the volume behaves (ProcParts, ROTanks)
> Scale resources when B9PS changes the volume

- Source/Tanks/ModuleFuelTanks.cs
- Source/Tanks/TankDefinition.cs
Allows pre-selecting the best available tank definition when a part gets plucked from the 🐱🅰️🪵. Also allows excluding -HP tanks from getting selected as the default.
> Set default tank type based of order of preference

- RealFuels/SquadExpansion_modularFuelTanks.cfg
Already correctly configured in https://github.com/KSP-RO/RealFuels/blob/de4ad0ca047631d9d88d882d968a6897187ccb52/ModularFuelTanks/Squad_MakingHistory.cfg (why are there 2? idek)
Fix https://github.com/KSP-RO/RealFuels/issues/344
Size1p5_Monoprop = https://wiki.kerbalspaceprogram.com/wiki/FL-R400_RCS_Fuel_Tank/Box
MonoPropMini = https://wiki.kerbalspaceprogram.com/wiki/Stratus-V_Minified_Monopropellant_Tank
> Fix RCS tank types
